### ISSUE TITLE
(UndefinedFunctionError) undefined function: Instream.Pool.Worker.terminate/2

### ISSUE THREAD

**Issue by MadRabbit** [mneudert/instream#3]
Hey Marc,

I'm having a bit of a problem with the lib, could you help me a bit? I'm just trying it out, so I've set up a config and stuff. Started a link and then i'm just trying to drop create a database and it explodes like so

```
14:30:38.189 [error] GenServer #PID<0.447.0> terminating
Last message: {:execute, %Instream.Query{payload: "DROP DATABASE blah_test", type: :cluster}, []}
State: [module: Blah.Database, writer: Instream.Writer.JSON, otp_app: :blah_app, auth: [username: "blah", password: "blah"], hosts: ["localhost"], pool: [max_overflow: 0, size: 1], port: 8086, scheme: "http"]
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :"function not exported"
        Instream.Pool.Worker.terminate({:noproc, {:gen_server, :call, [:hackney_manager, {:new_request, #PID<0.447.0>, #Reference<0.0.3.1417>, {:client, :undefined, :hackney_dummy_metrics, :hackney_tcp_transport, 'localhost', 8086, "localhost:8086", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, ...}}, :infinity]}}, [module: Blah.Database, writer: Instream.Writer.JSON, otp_app: :blah_app, auth: [username: "blah", password: "blah"], hosts: ["localhost"], pool: [max_overflow: 0, size: 1], port: 8086, scheme: "http"])
        (stdlib) gen_server.erl:643: :gen_server.try_terminate/3
        (stdlib) gen_server.erl:809: :gen_server.terminate/7
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
** (exit) exited in: GenServer.call(#PID<0.447.0>, {:execute, %Instream.Query{payload: "DROP DATABASE blah_test", type: :cluster}, []}, 5000)
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function: Instream.Pool.Worker.terminate/2
            Instream.Pool.Worker.terminate({:noproc, {:gen_server, :call, [:hackney_manager, {:new_request, #PID<0.447.0>, #Reference<0.0.3.1417>, {:client, :undefined, :hackney_dummy_metrics, :hackney_tcp_transport, 'localhost', 8086, "localhost:8086", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, ...}}, :infinity]}}, [module: Blah.Database, writer: Instream.Writer.JSON, otp_app: :blah_app, auth: [username: "blah", password: "blah"], hosts: ["localhost"], pool: [max_overflow: 0, size: 1], port: 8086, scheme: "http"])
            (stdlib) gen_server.erl:643: :gen_server.try_terminate/3
            (stdlib) gen_server.erl:809: :gen_server.terminate/7
            (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    src/poolboy.erl:76: :poolboy.transaction/3
    test/test_helper.exs:3: (file)
    (elixir) lib/code.ex:307: Code.require_file/2
    (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
```

The code looks dead simple

```elixir
Supervisor.start_link(
  [ Blah.Database.child_spec ],
  strategy: :one_for_one
)

_ = "blah_test" |> Instream.Cluster.Database.drop()   |> Blah.Database.execute()
```

I'm no expert but it seems that erlang's poolboy behavior expects the `terminate/2` method on your `Pool.Worker` thing

I tried to define the method manually in my `deps/instream` copy. Didn't quite help. I'm a bit out of my depth there. So, if you could give it a thought, would be great. Thanks!

---

The env.

influxdb - 1.9.3 (vanilla install)
erlang - 7.0.3
elixir - 1.0.5
instream - github: "mneudert/instream"

let me know if you need any more details or want me to try something on my machine

**Comment by MadRabbit** [comment]
Just in case here is my `mix.lock`

```
%{"hackney": {:hex, :hackney, "1.3.1"},
  "idna": {:hex, :idna, "1.0.2"},
  "instream": {:git, "git://github.com/mneudert/instream.git", "da519f3450950e7ee79ad8f9c0d2e72d9b046093", []},
  "meck": {:hex, :meck, "0.8.3"},
  "mock": {:git, "git://github.com/jjh42/mock.git", "5a6bb6dd70ccc54997dda72f18f0ab85138c1253", []},
  "poison": {:hex, :poison, "1.5.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.5"}}
```

**Comment by mneudert** [comment]
Well, the `terminate/2` method is definitely not there and it is expected to blow up if there is any real error with the server.

Another problem may be a missing `:hackney` in the applications of your mix file. The first error line `Instream.Pool.Worker.terminate({:noproc, {:gen_server, :call, [:hackney_manager ...` at least looks like that. Could you check if that resolves your problems?

Then it is just a matter of fixing the docs to fix your problem. (And maybe finally completing the otp behaviour...)

**Comment by MadRabbit** [comment]
em... `hackney` is the first line on the `mix.lock` i posted. it's also in the `deps/` folder as well. it compiles and everything

**Comment by mneudert** [comment]
I am talking about `mix.exs` and the applications started there:

```elixir
  def application do
    [ applications: [ :hackney ]]
  end
```

That part is missing in the docs and might be the root of your problem.

**Comment by MadRabbit** [comment]
agh! that was it! and that's actually in your readme as well. sorry about that, totally my fault!

in any case thanks for the help and a quick answer. really appreciate it!

and thanks for the lib too! :)

**Comment by mneudert** [comment]
:relieved:
