### ISSUE TITLE
Influxdb may return a value without point character in `double` type field

### ISSUE THREAD

**Issue by Ma233** [mneudert/instream#69]
Influxdb returned a `"35"` as value in a `double` type field. The original value I wrote by connection was `String.to_float("35.00")`.

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of a float

    :erlang.binary_to_float("35")
    (instream 2.0.0-dev) lib/instream/decoder/csv.ex:58: Instream.Decoder.CSV.parse_datatypes/1
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (instream 2.0.0-dev) lib/instream/decoder/csv.ex:80: anonymous fn/4 in Instream.Decoder.CSV.parse_rows/1
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (instream 2.0.0-dev) lib/instream/connection/query_runner_v2.ex:75: Instream.Connection.QueryRunnerV2.read/3
```

Some version info:
```
{:instream, github: "mneudert/instream", ref: "6fff364132d048810e4e4ab0ce4d52d9cb654d0e"}
```
```
InfluxDB 2.0.9 (git: d1233b7951) build_date: 2021-09-24T20:04:53Z
```

**Comment by mneudert** [comment]
Should be fixed after the merge of #68.

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
